#!/usr/bin/env bash

# make_deck - A truly standalone pandoc beamer presentation generator
# Usage: make_deck input.md output.pdf [--theme THEME] [--theme-file NAME]
#        make_deck --import-theme template.pptx [--name mytheme]

set -e

# Configuration
SOURCE_FORMAT="markdown_strict+pipe_tables+backtick_code_blocks+auto_identifiers+strikeout+yaml_metadata_block+implicit_figures+all_symbols_escapable+link_attributes+smart+fenced_divs"

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to create embedded template file
create_template() {
    local temp_dir="$1"

    # Create the simple beamer template
    cat > "$temp_dir/simple_beamer.latex" << 'TEMPLATE_EOF'
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode$for(hyperrefoptions)$,$hyperrefoptions$$endfor$}{hyperref}
\PassOptionsToPackage{hyphens}{url}
$if(colorlinks)$
\PassOptionsToPackage{dvipsnames,svgnames*,x11names*}{xcolor}
$endif$
$if(dir)$
$if(latex-dir-rtl)$
\PassOptionsToPackage{RTLdocument}{bidi}
$endif$
$endif$
%
\documentclass[
$if(fontsize)$
  $fontsize$,
$endif$
$if(lang)$
  $babel-lang$,
$endif$
$if(papersize)$
  $papersize$paper,
$endif$
$if(beamer)$
  ignorenonframetext,
$if(handout)$
  handout,
$endif$
$if(aspectratio)$
  aspectratio=$aspectratio$,
$endif$
$endif$
$for(classoption)$
  $classoption$$sep$,
$endfor$
]{$documentclass$}

$if(beamer)$
$if(background-image)$
\usebackgroundtemplate{%
  \includegraphics[width=\paperwidth]{$background-image$}%
}
$endif$
\usepackage{pgfpages}
\setbeamertemplate{caption}[numbered]
\setbeamertemplate{caption label separator}{: }
\setbeamercolor{caption name}{fg=normal text.fg}
\beamertemplatenavigationsymbols$if(navigation)$$navigation$$else$empty$endif$

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% BEAMER THEME SELECTION
%
% Available built-in themes (27 total):
% AnnArbor, Antibes, Bergen, Berkeley, Berlin, Boadilla, CambridgeUS,
% Copenhagen, Darmstadt, Dresden, Frankfurt, Goettingen, Hannover, 
% Ilmenau, JuanLesPins, Luebeck, Madrid, Malmoe, Marburg, Montpellier,
% PaloAlto, Pittsburgh, Rochester, Singapore, Szeged, Warsaw, boxes, default
%
% Popular choices:
% - Frankfurt: Clean with navigation dots
% - Madrid: Simple and professional
% - Copenhagen: Modern blue theme
% - Berlin: Classic academic look
% - Boadilla: Minimal and elegant
% - CambridgeUS: Traditional university style
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

$if(theme)$
\usetheme[$for(themeoptions)$$themeoptions$$sep$,$endfor$]{$theme$}
$else$
\usetheme{default}  % Default theme if none specified
$endif$

$if(colortheme)$
\usecolortheme{$colortheme$}
$endif$
$if(fonttheme)$
\usefonttheme{$fonttheme$}
$endif$
$if(mainfont)$
\usefonttheme{serif} % use mainfont rather than sansfont for slide text
$endif$
$if(innertheme)$
\useinnertheme{$innertheme$}
$endif$
$if(outertheme)$
\useoutertheme{$outertheme$}
$endif$

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% POWERPOINT-STYLE CUSTOMIZATIONS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% --- Color scheme ---
\definecolor{pptPrimary}{RGB}{31,78,121}      % Dark corporate blue
\definecolor{pptAccent}{RGB}{68,114,196}       % Lighter blue for highlights
\definecolor{pptLightGray}{RGB}{242,242,242}   % Block backgrounds
\definecolor{pptDarkText}{RGB}{51,51,51}       % Near-black body text
\definecolor{pptMidGray}{RGB}{140,140,140}     % Subtitle/secondary text

\setbeamercolor{normal text}{fg=pptDarkText}
\setbeamercolor{structure}{fg=pptPrimary}
\setbeamercolor{alerted text}{fg=pptAccent}
\setbeamercolor{frametitle}{fg=pptPrimary,bg=}
\setbeamercolor{title}{fg=pptPrimary}
\setbeamercolor{subtitle}{fg=pptMidGray}
\setbeamercolor{author}{fg=pptDarkText}
\setbeamercolor{date}{fg=pptMidGray}
\setbeamercolor{institute}{fg=pptMidGray}
\setbeamercolor{item}{fg=pptPrimary}
\setbeamercolor{footline}{fg=pptMidGray,bg=white}

% --- Remove navigation chrome ---
\setbeamertemplate{headline}{}        % No header/navigation bar
\setbeamertemplate{navigation symbols}{}

% Minimal footline: just slide number, right-aligned
\setbeamertemplate{footline}{%
  \hfill%
  \usebeamercolor[fg]{footline}%
  \usebeamerfont{footline}%
  \insertframenumber\kern1.5em\vskip6pt%
}
\setbeamerfont{footline}{size=\scriptsize}

% --- Clean frame titles with accent underline ---
\setbeamerfont{frametitle}{size=\large,series=\bfseries}
\setbeamertemplate{frametitle}{%
  \vskip6pt%
  \usebeamerfont{frametitle}\usebeamercolor[fg]{frametitle}\insertframetitle%
  \vskip2pt%
  {\color{pptAccent}\rule{\textwidth}{0.8pt}}%
  \vskip4pt%
}

% --- PowerPoint-style title slide ---
\defbeamertemplate*{title page}{ppt}{%
  \vfill
  \begin{center}
    {\usebeamerfont{title}\usebeamercolor[fg]{title}\inserttitle\par}%
    \ifx\insertsubtitle\@empty\else
      \vskip8pt%
      {\usebeamerfont{subtitle}\usebeamercolor[fg]{subtitle}\insertsubtitle\par}%
    \fi
    \vskip20pt%
    {\color{pptAccent}\rule{0.4\textwidth}{1pt}\par}%
    \vskip20pt%
    {\usebeamerfont{author}\usebeamercolor[fg]{author}\insertauthor\par}%
    \ifx\insertinstitute\@empty\else
      \vskip4pt%
      {\usebeamerfont{institute}\usebeamercolor[fg]{institute}\insertinstitute\par}%
    \fi
    \vskip8pt%
    {\usebeamerfont{date}\usebeamercolor[fg]{date}\insertdate\par}%
  \end{center}
  \vfill
}
\setbeamerfont{title}{size=\LARGE,series=\bfseries}
\setbeamerfont{subtitle}{size=\large}
\setbeamerfont{author}{size=\normalsize}
\setbeamerfont{institute}{size=\small}
\setbeamerfont{date}{size=\small}

% --- Clean bullet points ---
\setbeamertemplate{itemize item}{\textbullet}
\setbeamertemplate{itemize subitem}{\textendash}
\setbeamertemplate{itemize subsubitem}{\raise0.5pt\hbox{\scalebox{0.6}{\textbullet}}}

% --- Softer blocks ---
\setbeamercolor{block title}{fg=pptPrimary,bg=}
\setbeamercolor{block body}{fg=pptDarkText,bg=pptLightGray}
\setbeamerfont{block title}{series=\bfseries}
\setbeamertemplate{blocks}[default]

\setbeamercolor{block title alerted}{fg=pptAccent,bg=}
\setbeamercolor{block body alerted}{fg=pptDarkText,bg=pptLightGray}
\setbeamercolor{block title example}{fg=pptPrimary,bg=}
\setbeamercolor{block body example}{fg=pptDarkText,bg=pptLightGray}

% --- More whitespace ---
\setbeamersize{text margin left=1.2cm,text margin right=1.2cm}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Fix strikeout compatibility
$if(strikeout)$
\usepackage[normalem]{ulem}
\newcommand{\st}[1]{\sout{#1}}
\pdfstringdefDisableCommands{\renewcommand{\sout}{}}
$endif$

% Code listing colors for better readability
\definecolor{blanchedalmond}{rgb}{1.0, 0.92, 0.8}
\definecolor{blond}{rgb}{0.98, 0.94, 0.75}

$for(beameroption)$
\setbeameroption{$beameroption$}
$endfor$
% Prevent slide breaks in the middle of a paragraph
\widowpenalties 1 10000
\raggedbottom
$if(section-titles)$
\setbeamertemplate{part page}{
  \centering
  \begin{beamercolorbox}[sep=16pt,center]{part title}
    \usebeamerfont{part title}\insertpart\par
  \end{beamercolorbox}
}
\setbeamertemplate{section page}{
  \centering
  \begin{beamercolorbox}[sep=12pt,center]{part title}
    \usebeamerfont{section title}\insertsection\par
  \end{beamercolorbox}
}
\setbeamertemplate{subsection page}{
  \centering
  \begin{beamercolorbox}[sep=8pt,center]{part title}
    \usebeamerfont{subsection title}\insertsubsection\par
  \end{beamercolorbox}
}
\AtBeginPart{
  \frame{\partpage}
}
\AtBeginSection{
  \ifbibliography
  \else
    \frame{\sectionpage}
  \fi
}
\AtBeginSubsection{
  \frame{\subsectionpage}
}
$endif$
$endif$
$if(beamerarticle)$
\usepackage{beamerarticle} % needs to be loaded first
$endif$
$if(fontfamily)$
\usepackage[$for(fontfamilyoptions)$$fontfamilyoptions$$sep$,$endfor$]{$fontfamily$}
$else$
\usepackage{lmodern}
$endif$
$if(linestretch)$
\usepackage{setspace}
$endif$
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[$if(fontenc)$$fontenc$$else$T1$endif$]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
$if(mathspec)$
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{unicode-math}
  \fi
$else$
  \usepackage{unicode-math}
$endif$
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
$if(mainfont)$
  \setmainfont[$for(mainfontoptions)$$mainfontoptions$$sep$,$endfor$]{$mainfont$}
$endif$
$if(sansfont)$
  \setsansfont[$for(sansfontoptions)$$sansfontoptions$$sep$,$endfor$]{$sansfont$}
$endif$
$if(monofont)$
  \setmonofont[$for(monofontoptions)$$monofontoptions$$sep$,$endfor$]{$monofont$}
$endif$
$for(fontfamilies)$
  \newfontfamily{$fontfamilies.name$}[$for(fontfamilies.options)$$fontfamilies.options$$sep$,$endfor$]{$fontfamilies.font$}
$endfor$
$if(mathfont)$
$if(mathspec)$
  \ifxetex
    \setmathfont(Digits,Latin,Greek)[$for(mathfontoptions)$$mathfontoptions$$sep$,$endfor$]{$mathfont$}
  \else
    \setmathfont[$for(mathfontoptions)$$mathfontoptions$$sep$,$endfor$]{$mathfont$}
  \fi
$else$
  \setmathfont[$for(mathfontoptions)$$mathfontoptions$$sep$,$endfor$]{$mathfont$}
$endif$
$endif$
$if(CJKmainfont)$
  \ifxetex
    \usepackage{xeCJK}
    \setCJKmainfont[$for(CJKoptions)$$CJKoptions$$sep$,$endfor$]{$CJKmainfont$}
  \fi
$endif$
$if(luatexjapresetoptions)$
  \ifluatex
    \usepackage[$for(luatexjapresetoptions)$$luatexjapresetoptions$$sep$,$endfor$]{luatexja-preset}
  \fi
$endif$
$if(CJKmainfont)$
  \ifluatex
    \usepackage[$for(luatexjafontspecoptions)$$luatexjafontspecoptions$$sep$,$endfor$]{luatexja-fontspec}
    \setmainjfont[$for(CJKoptions)$$CJKoptions$$sep$,$endfor$]{$CJKmainfont$}
  \fi
$endif$
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[$for(microtypeoptions)$$microtypeoptions$$sep$,$endfor$]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
$if(indent)$
$else$
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
$endif$
$if(verbatim-in-note)$
\usepackage{fancyvrb}
$endif$
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
$if(title-meta)$
  pdftitle={$title-meta$},
$endif$
$if(author-meta)$
  pdfauthor={$author-meta$},
$endif$
$if(lang)$
  pdflang={$lang$},
$endif$
$if(subject)$
  pdfsubject={$subject$},
$endif$
$if(keywords)$
  pdfkeywords={$for(keywords)$$keywords$$sep$, $endfor$},
$endif$
$if(colorlinks)$
  colorlinks=true,
  linkcolor=$if(linkcolor)$$linkcolor$$else$Maroon$endif$,
  filecolor=$if(filecolor)$$filecolor$$else$Maroon$endif$,
  citecolor=$if(citecolor)$$citecolor$$else$Blue$endif$,
  urlcolor=$if(urlcolor)$$urlcolor$$else$Blue$endif$,
$else$
  hidelinks,
$endif$
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
$if(verbatim-in-note)$
\VerbatimFootnotes % allow verbatim text in footnotes
$endif$
$if(geometry)$
$if(beamer)$
\geometry{$for(geometry)$$geometry$$sep$,$endfor$}
$else$
\usepackage[$for(geometry)$$geometry$$sep$,$endfor$]{geometry}
$endif$
$endif$
$if(beamer)$
\newif\ifbibliography
$endif$
$if(listings)$
\usepackage{listings}
\newcommand{\passthrough}[1]{#1}
\lstset{defaultdialect=sh}
\lstset{framexleftmargin=0mm, frame=trBL,backgroundcolor=\color{blanchedalmond!5},numbers=left,numberstyle=\scriptsize,basicstyle=\small}
\lstset{aboveskip=5mm,belowskip=5mm,xleftmargin=20pt,xrightmargin=5pt}
\lstset{breaklines=true,breakatwhitespace=true}
$endif$
$if(lhs)$
\lstnewenvironment{code}{\lstset{language=Haskell,basicstyle=\small\ttfamily}}{}
$endif$
$if(highlighting-macros)$
$highlighting-macros$
$endif$
$if(tables)$
\usepackage{longtable,booktabs}
$if(beamer)$
\usepackage{caption}
% Make caption package work with longtable
\makeatletter
\def\fnum@table{\tablename~\thetable}
\makeatother
% Define dummy 'none' counter for newer pandoc longtable output
\newcounter{none}
$else$
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
$endif$
$endif$
$if(graphics)$
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
$endif$
$if(links-as-notes)$
% Make links footnotes instead of hotlinks:
\DeclareRobustCommand{\href}[2]{#2\footnote{\url{#1}}}
$endif$
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
% Compatibility with newer pandoc versions
\providecommand{\pandocbounded}[1]{#1}
$if(numbersections)$
\setcounter{secnumdepth}{$if(secnumdepth)$$secnumdepth$$else$5$endif$}
$else$
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
$endif$

%
% When using babel or polyglossia with biblatex, loading csquotes is recommended 
% to ensure that quoted texts are typeset according to the rules of your main language.
%
\usepackage{csquotes}

%
% blockquote
%
\definecolor{blockquote-border}{RGB}{221,221,221}
\definecolor{blockquote-text}{RGB}{89,89,89}
\usepackage{mdframed}
\newmdenv[rightline=false,bottomline=false,topline=false,linewidth=3pt,linecolor=blockquote-border,skipabove=\parskip]{customblockquote}
\renewenvironment{quote}{\begin{customblockquote}\list{}{\rightmargin=0em\leftmargin=0em}%
\item\relax\color{blockquote-text}\ignorespaces}{\unskip\unskip\endlist\end{customblockquote}}

%
% Font configuration: Inter (PowerPoint-like) with Source Sans Pro fallback
% Source Code Pro for monospace text
%
$if(mainfont)$
$else$
\usepackage{sourcecodepro}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0
  % pdftex: use Source Sans Pro as fallback
  \usepackage[default]{sourcesanspro}
\else
  % xetex/luatex: try Inter, fall back to Source Sans Pro
  \IfFontExistsTF{Inter}{%
    \setsansfont[
      BoldFont={* Bold},
      ItalicFont={* Italic},
      BoldItalicFont={* Bold Italic}
    ]{Inter}%
  }{%
    \IfFontExistsTF{Source Sans Pro}{%
      \setsansfont{Source Sans Pro}%
    }{%
      % lmodern fallback (already loaded)
    }%
  }%
\fi

% XeLaTeX specific adjustments for straight quotes
\ifxetex
\makeatletter
\defaultfontfeatures[\ttfamily]
  { Numbers   = \sourcecodepro@figurestyle,
    Scale     = \SourceCodePro@scale,
    Extension = .otf }
\setmonofont
  [ UprightFont    = *-\sourcecodepro@regstyle,
    ItalicFont     = *-\sourcecodepro@regstyle It,
    BoldFont       = *-\sourcecodepro@boldstyle,
    BoldItalicFont = *-\sourcecodepro@boldstyle It ]
  {SourceCodePro}
\makeatother
\fi
$endif$

$if(beamer)$
$else$
$if(block-headings)$
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
$endif$
$endif$
$if(pagestyle)$
\pagestyle{$pagestyle$}
$endif$
$for(header-includes)$
$header-includes$
$endfor$
$if(lang)$
\ifxetex
  % Load polyglossia as late as possible: uses bidi with RTL langages (e.g. Hebrew, Arabic)
  \usepackage{polyglossia}
  \setmainlanguage[$polyglossia-lang.options$]{$polyglossia-lang.name$}
$for(polyglossia-otherlangs)$
  \setotherlanguage[$polyglossia-otherlangs.options$]{$polyglossia-otherlangs.name$}
$endfor$
\else
  \usepackage[shorthands=off,$for(babel-otherlangs)$$babel-otherlangs$,$endfor$main=$babel-lang$]{babel}
$if(babel-newcommands)$
  $babel-newcommands$
$endif$
\fi
$endif$
$if(dir)$
\ifxetex
  % Load bidi as late as possible as it modifies e.g. graphicx
  \usepackage{bidi}
\fi
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \TeXXeTstate=1
  \newcommand{\RL}[1]{\beginR #1\endR}
  \newcommand{\LR}[1]{\beginL #1\endL}
  \newenvironment{RTL}{\beginR}{\endR}
  \newenvironment{LTR}{\beginL}{\endL}
\fi
$endif$
$if(natbib)$
\usepackage[$natbiboptions$]{natbib}
\bibliographystyle{$if(biblio-style)$$biblio-style$$else$plainnat$endif$}
$endif$
$if(biblatex)$
\usepackage[$if(biblio-style)$style=$biblio-style$,$endif$$for(biblatexoptions)$$biblatexoptions$$sep$,$endfor$]{biblatex}
$for(bibliography)$
\addbibresource{$bibliography$}
$endfor$
$endif$

$if(title)$
\title{$title$$if(thanks)$\thanks{$thanks$}$endif$}
$endif$
$if(subtitle)$
$if(beamer)$
$else$
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
$endif$
\subtitle{$subtitle$}
$endif$
$if(author)$
\author{$for(author)$$author$$sep$ \and $endfor$}
$endif$
\date{$date$}
$if(beamer)$
$if(institute)$
\institute{$for(institute)$$institute$$sep$ \and $endfor$}
$endif$
$if(titlegraphic)$
\titlegraphic{\includegraphics{$titlegraphic$}}
$endif$
$if(logo)$
\logo{\includegraphics{$logo$}}
$endif$
$endif$

\begin{document}
$if(has-frontmatter)$
\frontmatter
$endif$
$if(title)$
$if(beamer)$
\frame{\titlepage}
$else$
\maketitle
$endif$
$if(abstract)$
\begin{abstract}
$abstract$
\end{abstract}
$endif$
$endif$

$for(include-before)$
$include-before$

$endfor$
$if(toc)$
$if(toc-title)$
\renewcommand*\contentsname{$toc-title$}
$endif$
$if(beamer)$
\begin{frame}
$if(toc-title)$
  \frametitle{$toc-title$}
$endif$
  \tableofcontents[hideallsubsections]
\end{frame}
$else$
{
$if(colorlinks)$
\hypersetup{linkcolor=$if(toccolor)$$toccolor$$else$$endif$}
$endif$
\setcounter{tocdepth}{$toc-depth$}
\tableofcontents
}
$endif$
$endif$
$if(lot)$
\listoftables
$endif$
$if(lof)$
\listoffigures
$endif$
$if(linestretch)$
\setstretch{$linestretch$}
$endif$
$if(has-frontmatter)$
\mainmatter
$endif$
$body$

$if(has-frontmatter)$
\backmatter
$endif$
$if(natbib)$
$if(bibliography)$
$if(biblio-title)$
$if(has-chapters)$
\renewcommand\bibname{$biblio-title$}
$else$
\renewcommand\refname{$biblio-title$}
$endif$
$endif$
$if(beamer)$
\begin{frame}[allowframebreaks]{$biblio-title$}
  \bibliographytrue
$endif$
  \bibliography{$for(bibliography)$$bibliography$$sep$,$endfor$}
$if(beamer)$
\end{frame}
$endif$

$endif$
$endif$
$if(biblatex)$
$if(beamer)$
\begin{frame}[allowframebreaks]{$biblio-title$}
  \bibliographytrue
  \printbibliography[heading=none]
\end{frame}
$else$
\printbibliography$if(biblio-title)$[title=$biblio-title$]$endif$
$endif$

$endif$
$for(include-after)$
$include-after$

$endfor$
\end{document}
TEMPLATE_EOF
}

# Function to create embedded Python extractor
create_extractor() {
    local temp_dir="$1"

    cat > "$temp_dir/extract_pptx_theme.py" << 'EXTRACTOR_EOF'
#!/usr/bin/env python3

"""
Extract color and font theme from a .pptx file and generate a Beamer LaTeX snippet.

Reads ppt/theme/theme1.xml from the PPTX (ZIP) archive, maps PowerPoint color
slots to the 5 ppt* Beamer color names used by simple_beamer.latex, and writes
a .latex file that cleanly overrides the template defaults.
"""

import argparse
import os
import re
import sys
import zipfile
import xml.etree.ElementTree as ET

NS = {"a": "http://schemas.openxmlformats.org/drawingml/2006/main"}

# Fallback defaults matching simple_beamer.latex built-in palette
FALLBACK_COLORS = {
    "dk1": "333333",
    "dk2": "1F4E79",
    "lt1": "FFFFFF",
    "lt2": "F2F2F2",
    "accent1": "4472C4",
    "accent2": "ED7D31",
    "accent3": "A5A5A5",
    "accent4": "FFC000",
    "accent5": "5B9BD5",
    "accent6": "70AD47",
    "hlink": "0563C1",
    "folHlink": "954F72",
}


def find_theme_xml(zf):
    """Locate the theme XML inside the PPTX archive."""
    primary = "ppt/theme/theme1.xml"
    if primary in zf.namelist():
        return primary
    for name in sorted(zf.namelist()):
        if name.startswith("ppt/theme/") and name.endswith(".xml"):
            return name
    return None


def extract_color(element):
    """Extract a hex color string from a color scheme child element."""
    srgb = element.find("a:srgbClr", NS)
    if srgb is not None:
        return srgb.get("val", "")

    sys_clr = element.find("a:sysClr", NS)
    if sys_clr is not None:
        last = sys_clr.get("lastClr", "")
        if last:
            return last

    return ""


def extract_colors(tree):
    """Extract all color slots from the theme's clrScheme."""
    colors = dict(FALLBACK_COLORS)
    clr_scheme = tree.find(".//a:clrScheme", NS)
    if clr_scheme is None:
        print("Warning: No <a:clrScheme> found, using fallback colors.", file=sys.stderr)
        return colors

    for slot in FALLBACK_COLORS:
        elem = clr_scheme.find(f"a:{slot}", NS)
        if elem is not None:
            val = extract_color(elem)
            if val:
                colors[slot] = val.upper()

    return colors


def extract_fonts(tree):
    """Extract major/minor Latin font names from the theme's fontScheme."""
    fonts = {"major": None, "minor": None}
    font_scheme = tree.find(".//a:fontScheme", NS)
    if font_scheme is None:
        return fonts

    for key, tag in [("major", "a:majorFont"), ("minor", "a:minorFont")]:
        parent = font_scheme.find(tag, NS)
        if parent is not None:
            latin = parent.find("a:latin", NS)
            if latin is not None:
                typeface = latin.get("typeface", "")
                # Skip placeholder values like +mj-lt / +mn-lt
                if typeface and not typeface.startswith("+"):
                    fonts[key] = typeface

    return fonts


def hex_to_rgb(hexval):
    """Convert a 6-char hex string to an (R, G, B) tuple."""
    h = hexval.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


def weighted_avg_color(hex_a, hex_b, weight_a=0.55):
    """Blend two hex colors with the given weight for color A."""
    ra, ga, ba = hex_to_rgb(hex_a)
    rb, gb, bb = hex_to_rgb(hex_b)
    w = weight_a
    r = int(ra * w + rb * (1 - w))
    g = int(ga * w + gb * (1 - w))
    b = int(ba * w + bb * (1 - w))
    return f"{r:02X}{g:02X}{b:02X}"


def generate_latex(colors, fonts, theme_name):
    """Generate the .latex snippet content."""
    dk1 = colors["dk1"]
    dk2 = colors["dk2"]
    lt2 = colors["lt2"]
    accent1 = colors["accent1"]
    mid = weighted_avg_color(dk1, lt2)

    r_dk1, g_dk1, b_dk1 = hex_to_rgb(dk1)
    r_dk2, g_dk2, b_dk2 = hex_to_rgb(dk2)
    r_lt2, g_lt2, b_lt2 = hex_to_rgb(lt2)
    r_acc, g_acc, b_acc = hex_to_rgb(accent1)
    r_mid, g_mid, b_mid = hex_to_rgb(mid)

    lines = []
    lines.append(f"% Beamer color theme extracted from: {theme_name}")
    lines.append(f"% Generated by make_deck --import-theme")
    lines.append("")

    # Color definitions
    lines.append("% === Color overrides ===")
    lines.append(f"\\definecolor{{pptDarkText}}{{RGB}}{{{r_dk1},{g_dk1},{b_dk1}}}      % dk1: body text")
    lines.append(f"\\definecolor{{pptPrimary}}{{RGB}}{{{r_dk2},{g_dk2},{b_dk2}}}       % dk2: headings, structure")
    lines.append(f"\\definecolor{{pptLightGray}}{{RGB}}{{{r_lt2},{g_lt2},{b_lt2}}}     % lt2: block backgrounds")
    lines.append(f"\\definecolor{{pptAccent}}{{RGB}}{{{r_acc},{g_acc},{b_acc}}}        % accent1: highlights, rules")
    lines.append(f"\\definecolor{{pptMidGray}}{{RGB}}{{{r_mid},{g_mid},{b_mid}}}       % derived: subtitle, footline")
    lines.append("")

    # Beamer color re-applications
    lines.append("% === Beamer role assignments ===")
    lines.append("\\setbeamercolor{normal text}{fg=pptDarkText}")
    lines.append("\\setbeamercolor{structure}{fg=pptPrimary}")
    lines.append("\\setbeamercolor{alerted text}{fg=pptAccent}")
    lines.append("\\setbeamercolor{frametitle}{fg=pptPrimary,bg=}")
    lines.append("\\setbeamercolor{title}{fg=pptPrimary}")
    lines.append("\\setbeamercolor{subtitle}{fg=pptMidGray}")
    lines.append("\\setbeamercolor{author}{fg=pptDarkText}")
    lines.append("\\setbeamercolor{date}{fg=pptMidGray}")
    lines.append("\\setbeamercolor{institute}{fg=pptMidGray}")
    lines.append("\\setbeamercolor{item}{fg=pptPrimary}")
    lines.append("\\setbeamercolor{footline}{fg=pptMidGray,bg=white}")
    lines.append("\\setbeamercolor{block title}{fg=pptPrimary,bg=}")
    lines.append("\\setbeamercolor{block body}{fg=pptDarkText,bg=pptLightGray}")
    lines.append("\\setbeamercolor{block title alerted}{fg=pptAccent,bg=}")
    lines.append("\\setbeamercolor{block body alerted}{fg=pptDarkText,bg=pptLightGray}")
    lines.append("\\setbeamercolor{block title example}{fg=pptPrimary,bg=}")
    lines.append("\\setbeamercolor{block body example}{fg=pptDarkText,bg=pptLightGray}")
    lines.append("")

    # Font override (XeTeX/LuaTeX only)
    heading_font = fonts.get("major")
    body_font = fonts.get("minor")
    if heading_font or body_font:
        lines.append("% === Font overrides (XeTeX/LuaTeX only) ===")
        if body_font:
            lines.append(f"\\IfFontExistsTF{{{body_font}}}{{\\setsansfont{{{body_font}}}}}{{}}%")
        if heading_font and heading_font != body_font:
            lines.append(f"% Heading font: {heading_font}")
            lines.append(f"% (To use separately, set \\setbeamerfont{{frametitle}}{{...}} manually)")
        lines.append("")

    # Reference: additional accent colors (commented out)
    lines.append("% === Additional accent colors (for reference) ===")
    for i in range(2, 7):
        key = f"accent{i}"
        if key in colors:
            r, g, b = hex_to_rgb(colors[key])
            lines.append(f"% \\definecolor{{pptAccent{i}}}{{RGB}}{{{r},{g},{b}}}  % {key}")

    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Extract a color/font theme from a .pptx file for Beamer"
    )
    parser.add_argument("input", help="Path to the .pptx file")
    parser.add_argument("--name", required=True, help="Theme name for the output file")
    parser.add_argument(
        "--output-dir",
        default=os.path.expanduser("~/.make_deck/themes"),
        help="Directory to write the .latex snippet (default: ~/.make_deck/themes)",
    )
    args = parser.parse_args()

    if not os.path.isfile(args.input):
        print(f"Error: File not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    if not zipfile.is_zipfile(args.input):
        print(f"Error: Not a valid .pptx (ZIP) file: {args.input}", file=sys.stderr)
        sys.exit(1)

    with zipfile.ZipFile(args.input, "r") as zf:
        theme_path = find_theme_xml(zf)
        if theme_path is None:
            print("Error: No theme XML found in the .pptx file.", file=sys.stderr)
            sys.exit(1)

        with zf.open(theme_path) as f:
            tree = ET.parse(f)

    colors = extract_colors(tree)
    fonts = extract_fonts(tree)
    latex = generate_latex(colors, fonts, os.path.basename(args.input))

    os.makedirs(args.output_dir, exist_ok=True)
    out_path = os.path.join(args.output_dir, f"{args.name}.latex")
    with open(out_path, "w") as f:
        f.write(latex)

    print(out_path)


if __name__ == "__main__":
    main()

EXTRACTOR_EOF
}

# Function to show usage
show_usage() {
    cat << EOF
Usage: make_deck input.md output.pdf [OPTIONS]
       make_deck --import-theme template.pptx [--name mytheme]

A portable pandoc beamer presentation generator.

Build mode:
  input.md         Input Markdown file
  output.pdf       Output PDF file
  --theme THEME    Beamer theme name (default: default)
  --theme-file NAME  Apply a saved color theme from ~/.make_deck/themes/

Import mode:
  --import-theme FILE  Extract colors/fonts from a .pptx file
  --name NAME          Theme name (default: derived from filename)

Available beamer themes:
  AnnArbor, Antibes, Bergen, Berkeley, Berlin, Boadilla, CambridgeUS,
  Copenhagen, Darmstadt, Dresden, Frankfurt, Goettingen, Hannover,
  Ilmenau, JuanLesPins, Luebeck, Madrid, Malmoe, Marburg, Montpellier,
  PaloAlto, Pittsburgh, Rochester, Singapore, Szeged, Warsaw, boxes, default

Examples:
  make_deck presentation.md presentation.pdf
  make_deck slides.md slides.pdf --theme Copenhagen
  make_deck --import-theme corporate.pptx --name corporate
  make_deck slides.md slides.pdf --theme-file corporate

Requirements:
  - pandoc
  - python3 (for --import-theme only)
  - One of: tectonic, lualatex, xelatex
EOF
}

# ── Argument parsing ──────────────────────────────────────────────

# Check for help flag early
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    show_usage
    exit 0
fi

# Detect mode: import or build
MODE="build"
IMPORT_FILE=""
THEME_NAME=""
INPUT_FILE=""
OUTPUT_FILE=""
THEME="default"
THEME_FILE=""

if [ "$1" = "--import-theme" ]; then
    MODE="import"
    shift
    IMPORT_FILE="$1"
    shift || true
    # Parse remaining import-mode flags
    while [ $# -gt 0 ]; do
        case "$1" in
            --name)
                THEME_NAME="$2"
                shift 2
                ;;
            *)
                echo "Error: Unknown option '$1' in import mode" >&2
                show_usage >&2
                exit 1
                ;;
        esac
    done
else
    # Build mode: first two positional args are input and output
    if [ $# -lt 2 ]; then
        echo "Error: Missing required arguments." >&2
        show_usage >&2
        exit 1
    fi
    INPUT_FILE="$1"
    OUTPUT_FILE="$2"
    shift 2
    # Parse remaining build-mode flags
    while [ $# -gt 0 ]; do
        case "$1" in
            --theme)
                THEME="$2"
                shift 2
                ;;
            --theme-file)
                THEME_FILE="$2"
                shift 2
                ;;
            *)
                echo "Error: Unknown option '$1'" >&2
                show_usage >&2
                exit 1
                ;;
        esac
    done
fi

# ── Import mode ───────────────────────────────────────────────────

if [ "$MODE" = "import" ]; then
    if [ -z "$IMPORT_FILE" ]; then
        echo "Error: No .pptx file specified." >&2
        show_usage >&2
        exit 1
    fi

    if [ ! -f "$IMPORT_FILE" ]; then
        echo "Error: File not found: $IMPORT_FILE" >&2
        exit 1
    fi

    if ! command_exists python3; then
        echo "Error: python3 is required for --import-theme." >&2
        exit 1
    fi

    # Derive theme name from filename if not provided
    if [ -z "$THEME_NAME" ]; then
        THEME_NAME=$(basename "$IMPORT_FILE" .pptx)
        # Lowercase and replace non-alnum with underscores
        THEME_NAME=$(echo "$THEME_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/_/g' | sed 's/__*/_/g' | sed 's/^_//;s/_$//')
    fi

    THEMES_DIR="$HOME/.make_deck/themes"
    mkdir -p "$THEMES_DIR"

    # Write embedded extractor to temp file
    TEMP_DIR=$(mktemp -d)
    trap "rm -rf '$TEMP_DIR'" EXIT
    create_extractor "$TEMP_DIR"

    OUTPUT_PATH=$(python3 "$TEMP_DIR/extract_pptx_theme.py" "$IMPORT_FILE" --name "$THEME_NAME" --output-dir "$THEMES_DIR")

    echo "Theme extracted: $OUTPUT_PATH"
    echo ""
    echo "Use it with:"
    echo "  make_deck slides.md slides.pdf --theme-file $THEME_NAME"
    exit 0
fi

# ── Build mode ────────────────────────────────────────────────────

# Validate input file
if [ ! -f "$INPUT_FILE" ]; then
    echo "Error: Input file '$INPUT_FILE' not found." >&2
    exit 1
fi

# Check for required dependencies
if ! command_exists pandoc; then
    echo "Error: pandoc is not installed or not in PATH." >&2
    echo "Install with: brew install pandoc (macOS) or see https://pandoc.org/installing.html" >&2
    exit 1
fi

# Choose a PDF engine
PDF_ENGINE=""
if command_exists tectonic; then
    PDF_ENGINE="tectonic"
elif command_exists lualatex; then
    PDF_ENGINE="lualatex"
elif command_exists xelatex; then
    PDF_ENGINE="xelatex"
else
    echo "Error: No TeX engine found (tectonic/lualatex/xelatex)." >&2
    echo "Install one of:" >&2
    echo "  - tectonic: brew install tectonic (recommended on macOS)" >&2
    echo "  - TeX distribution: brew install --cask mactex-no-gui" >&2
    exit 1
fi

echo "Using PDF engine: $PDF_ENGINE"

# Get current date
DATE_COVER=$(date "+%d %B %Y")

# Create temporary directory for templates
TEMP_DIR=$(mktemp -d)
trap "rm -rf '$TEMP_DIR'" EXIT

# Create embedded template
create_template "$TEMP_DIR"

# Build pandoc command using templates from temp directory
PANDOC_CMD=(
    pandoc
    -s
    --dpi=300
    --slide-level 2
    --toc
    --listings
    --shift-heading-level=0
    --template "$TEMP_DIR/simple_beamer.latex"
    --pdf-engine "$PDF_ENGINE"
    -f "$SOURCE_FORMAT"
    -M "date=$DATE_COVER"
    -V classoption:aspectratio=169
    -V theme="$THEME"
    --highlight-style=tango
    -t beamer
    "$INPUT_FILE"
    -o "$OUTPUT_FILE"
)

# Apply custom theme file if specified
if [ -n "$THEME_FILE" ]; then
    RESOLVED_THEME_FILE="$HOME/.make_deck/themes/$THEME_FILE.latex"
    if [ ! -f "$RESOLVED_THEME_FILE" ]; then
        echo "Error: Theme file not found: $RESOLVED_THEME_FILE" >&2
        echo "Import a theme first with: make_deck --import-theme template.pptx --name $THEME_FILE" >&2
        exit 1
    fi
    PANDOC_CMD+=(-H "$RESOLVED_THEME_FILE")
fi

# Execute pandoc command
echo "Generating PDF: $OUTPUT_FILE"
"${PANDOC_CMD[@]}"

if [ $? -eq 0 ]; then
    echo "Successfully generated: $OUTPUT_FILE"
else
    echo "Error: Failed to generate PDF" >&2
    exit 1
fi
