#!/usr/bin/env python3

"""
Extract color and font theme from a .pptx file and generate a Beamer LaTeX snippet.

Reads ppt/theme/theme1.xml from the PPTX (ZIP) archive, maps PowerPoint color
slots to the 5 ppt* Beamer color names used by simple_beamer.latex, and writes
a .latex file that cleanly overrides the template defaults.
"""

import argparse
import os
import re
import sys
import zipfile
import xml.etree.ElementTree as ET

NS = {"a": "http://schemas.openxmlformats.org/drawingml/2006/main"}

# Fallback defaults matching simple_beamer.latex built-in palette
FALLBACK_COLORS = {
    "dk1": "333333",
    "dk2": "1F4E79",
    "lt1": "FFFFFF",
    "lt2": "F2F2F2",
    "accent1": "4472C4",
    "accent2": "ED7D31",
    "accent3": "A5A5A5",
    "accent4": "FFC000",
    "accent5": "5B9BD5",
    "accent6": "70AD47",
    "hlink": "0563C1",
    "folHlink": "954F72",
}


def find_theme_xml(zf):
    """Locate the theme XML inside the PPTX archive."""
    primary = "ppt/theme/theme1.xml"
    if primary in zf.namelist():
        return primary
    for name in sorted(zf.namelist()):
        if name.startswith("ppt/theme/") and name.endswith(".xml"):
            return name
    return None


def extract_color(element):
    """Extract a hex color string from a color scheme child element."""
    srgb = element.find("a:srgbClr", NS)
    if srgb is not None:
        return srgb.get("val", "")

    sys_clr = element.find("a:sysClr", NS)
    if sys_clr is not None:
        last = sys_clr.get("lastClr", "")
        if last:
            return last

    return ""


def extract_colors(tree):
    """Extract all color slots from the theme's clrScheme."""
    colors = dict(FALLBACK_COLORS)
    clr_scheme = tree.find(".//a:clrScheme", NS)
    if clr_scheme is None:
        print("Warning: No <a:clrScheme> found, using fallback colors.", file=sys.stderr)
        return colors

    for slot in FALLBACK_COLORS:
        elem = clr_scheme.find(f"a:{slot}", NS)
        if elem is not None:
            val = extract_color(elem)
            if val:
                colors[slot] = val.upper()

    return colors


def extract_fonts(tree):
    """Extract major/minor Latin font names from the theme's fontScheme."""
    fonts = {"major": None, "minor": None}
    font_scheme = tree.find(".//a:fontScheme", NS)
    if font_scheme is None:
        return fonts

    for key, tag in [("major", "a:majorFont"), ("minor", "a:minorFont")]:
        parent = font_scheme.find(tag, NS)
        if parent is not None:
            latin = parent.find("a:latin", NS)
            if latin is not None:
                typeface = latin.get("typeface", "")
                # Skip placeholder values like +mj-lt / +mn-lt
                if typeface and not typeface.startswith("+"):
                    fonts[key] = typeface

    return fonts


def hex_to_rgb(hexval):
    """Convert a 6-char hex string to an (R, G, B) tuple."""
    h = hexval.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


def weighted_avg_color(hex_a, hex_b, weight_a=0.55):
    """Blend two hex colors with the given weight for color A."""
    ra, ga, ba = hex_to_rgb(hex_a)
    rb, gb, bb = hex_to_rgb(hex_b)
    w = weight_a
    r = int(ra * w + rb * (1 - w))
    g = int(ga * w + gb * (1 - w))
    b = int(ba * w + bb * (1 - w))
    return f"{r:02X}{g:02X}{b:02X}"


def generate_latex(colors, fonts, theme_name):
    """Generate the .latex snippet content."""
    dk1 = colors["dk1"]
    dk2 = colors["dk2"]
    lt2 = colors["lt2"]
    accent1 = colors["accent1"]
    mid = weighted_avg_color(dk1, lt2)

    r_dk1, g_dk1, b_dk1 = hex_to_rgb(dk1)
    r_dk2, g_dk2, b_dk2 = hex_to_rgb(dk2)
    r_lt2, g_lt2, b_lt2 = hex_to_rgb(lt2)
    r_acc, g_acc, b_acc = hex_to_rgb(accent1)
    r_mid, g_mid, b_mid = hex_to_rgb(mid)

    lines = []
    lines.append(f"% Beamer color theme extracted from: {theme_name}")
    lines.append(f"% Generated by make_deck --import-theme")
    lines.append("")

    # Color definitions
    lines.append("% === Color overrides ===")
    lines.append(f"\\definecolor{{pptDarkText}}{{RGB}}{{{r_dk1},{g_dk1},{b_dk1}}}      % dk1: body text")
    lines.append(f"\\definecolor{{pptPrimary}}{{RGB}}{{{r_dk2},{g_dk2},{b_dk2}}}       % dk2: headings, structure")
    lines.append(f"\\definecolor{{pptLightGray}}{{RGB}}{{{r_lt2},{g_lt2},{b_lt2}}}     % lt2: block backgrounds")
    lines.append(f"\\definecolor{{pptAccent}}{{RGB}}{{{r_acc},{g_acc},{b_acc}}}        % accent1: highlights, rules")
    lines.append(f"\\definecolor{{pptMidGray}}{{RGB}}{{{r_mid},{g_mid},{b_mid}}}       % derived: subtitle, footline")
    lines.append("")

    # Beamer color re-applications
    lines.append("% === Beamer role assignments ===")
    lines.append("\\setbeamercolor{normal text}{fg=pptDarkText}")
    lines.append("\\setbeamercolor{structure}{fg=pptPrimary}")
    lines.append("\\setbeamercolor{alerted text}{fg=pptAccent}")
    lines.append("\\setbeamercolor{frametitle}{fg=pptPrimary,bg=}")
    lines.append("\\setbeamercolor{title}{fg=pptPrimary}")
    lines.append("\\setbeamercolor{subtitle}{fg=pptMidGray}")
    lines.append("\\setbeamercolor{author}{fg=pptDarkText}")
    lines.append("\\setbeamercolor{date}{fg=pptMidGray}")
    lines.append("\\setbeamercolor{institute}{fg=pptMidGray}")
    lines.append("\\setbeamercolor{item}{fg=pptPrimary}")
    lines.append("\\setbeamercolor{footline}{fg=pptMidGray,bg=white}")
    lines.append("\\setbeamercolor{block title}{fg=pptPrimary,bg=}")
    lines.append("\\setbeamercolor{block body}{fg=pptDarkText,bg=pptLightGray}")
    lines.append("\\setbeamercolor{block title alerted}{fg=pptAccent,bg=}")
    lines.append("\\setbeamercolor{block body alerted}{fg=pptDarkText,bg=pptLightGray}")
    lines.append("\\setbeamercolor{block title example}{fg=pptPrimary,bg=}")
    lines.append("\\setbeamercolor{block body example}{fg=pptDarkText,bg=pptLightGray}")
    lines.append("")

    # Font override (XeTeX/LuaTeX only)
    heading_font = fonts.get("major")
    body_font = fonts.get("minor")
    if heading_font or body_font:
        lines.append("% === Font overrides (XeTeX/LuaTeX only) ===")
        if body_font:
            lines.append(f"\\IfFontExistsTF{{{body_font}}}{{\\setsansfont{{{body_font}}}}}{{}}%")
        if heading_font and heading_font != body_font:
            lines.append(f"% Heading font: {heading_font}")
            lines.append(f"% (To use separately, set \\setbeamerfont{{frametitle}}{{...}} manually)")
        lines.append("")

    # Reference: additional accent colors (commented out)
    lines.append("% === Additional accent colors (for reference) ===")
    for i in range(2, 7):
        key = f"accent{i}"
        if key in colors:
            r, g, b = hex_to_rgb(colors[key])
            lines.append(f"% \\definecolor{{pptAccent{i}}}{{RGB}}{{{r},{g},{b}}}  % {key}")

    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Extract a color/font theme from a .pptx file for Beamer"
    )
    parser.add_argument("input", help="Path to the .pptx file")
    parser.add_argument("--name", required=True, help="Theme name for the output file")
    parser.add_argument(
        "--output-dir",
        default=os.path.expanduser("~/.make_deck/themes"),
        help="Directory to write the .latex snippet (default: ~/.make_deck/themes)",
    )
    args = parser.parse_args()

    if not os.path.isfile(args.input):
        print(f"Error: File not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    if not zipfile.is_zipfile(args.input):
        print(f"Error: Not a valid .pptx (ZIP) file: {args.input}", file=sys.stderr)
        sys.exit(1)

    with zipfile.ZipFile(args.input, "r") as zf:
        theme_path = find_theme_xml(zf)
        if theme_path is None:
            print("Error: No theme XML found in the .pptx file.", file=sys.stderr)
            sys.exit(1)

        with zf.open(theme_path) as f:
            tree = ET.parse(f)

    colors = extract_colors(tree)
    fonts = extract_fonts(tree)
    latex = generate_latex(colors, fonts, os.path.basename(args.input))

    os.makedirs(args.output_dir, exist_ok=True)
    out_path = os.path.join(args.output_dir, f"{args.name}.latex")
    with open(out_path, "w") as f:
        f.write(latex)

    print(out_path)


if __name__ == "__main__":
    main()
